---
resource_pools:
  - name: openvpn
    network: openvpn
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      ram: 3840
      disk: 4096
      cpu: 2

compilation:
  workers: 3
  network: openvpn
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 2
    disk: 8096
    ram: 3840


jobs:
  - name: openvpn
    resource_pool: openvpn
