---
meta:
  azs:
    z1: (( param "What availability zone should your openvpn_z1 VMs be in?" ))
    z2: (( param "What availability zone should your openvpn_z2 VMs be in?" ))
resource_pools:
  - name: openvpn_z1
    network: openvpn_z1
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( grab meta.azs.z1 ))
      elbs: (( grab meta.elbs ))
  - name: openvpn_z2
    network: openvpn_z2
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( grab meta.azs.z2 ))
      elbs: (( grab meta.elbs ))

compilation:
  workers: 3
  network: openvpn_z1
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: (( grab meta.azs.z1 ))

jobs:
  - name: openvpn_z1
    resource_pool: openvpn_z1
  - name: openvpn_z2
    resource_pool: openvpn_z2
